- apps/governance/src/components/governance/proposals/ContainerProposals.tsx
- apps/governance/src/components/governance/proposals/ProposalCard.tsx
This PR fixes the governance cards height to expand and fill empty spaces
> fix: Unify gpvernance card height

- packages/evmos-wallet/src/internal/wallet/functionality/signing.ts
- packages/evmos-wallet/src/internal/wallet/functionality/signing/genericSigner.ts
This PR removes the Promise.reject so the snackbar is displayed.
The problem was that the return for the signing function was returning a promise and it should only return the information so the snackbar can read it and display it properly. 
Before:
`uncaught (in promise) {error: true, message: 'Transaction Failed Fee changed while sending transaction, please try again', txhash: '0x0'}`
After trying to claim rewards:
> fix: remove Promise.reject

- apps/assets/pages/index.tsx
- apps/assets/src/components/asset/HeadComponent.tsx
- apps/governance/pages/index.tsx
- apps/governance/src/components/governance/HeadComponent.tsx
- apps/mission/pages/index.tsx
- apps/mission/src/components/mission/HeadComponent.tsx
- apps/staking/pages/index.tsx
- apps/staking/src/components/staking/HeadComponent.tsx
This PR adds the meta tags for each of the pages: Mission Control, governance and staking. 
Assets page already has this information. The keywords and description were updated.
> feat: add meta tags to each of the pages

- CHANGELOG.md
- packages/evmos-wallet/package.json
- packages/evmos-wallet/src/internal/wallet/functionality/keplr/keplr.tsx
- packages/evmos-wallet/src/internal/wallet/functionality/metamask/metamask.tsx
- packages/evmos-wallet/src/wallet/ButtonWalletConnection.tsx
Problem: Every time the user goes to a different page on the dashboard, the snackbar keeps coming up saying that my wallet is connected.
With this PR the connected snackbar will only appear if the user clicks on connect wallet button
Changes: 
- Disconnect button: add `RemoveProviderFromLocalStorage`
- Get the provider value from localStorage and compare it with the provider key. If they are the same, the snackbar will not show. 
https://user-images.githubusercontent.com/40247040/235127389-2a709a03-35d2-4af2-a743-adaf01736830.mov
> fix: show connected snackbar only if the user clicks on connect wallet

- CHANGELOG.md
- package.json
This PR simple updates the change log release version and also bumps the main package.json version
> chore: update release version to 1.0.1

- CHANGELOG.md
- apps/mission/setup-redirects.sh
- package.json
This Pr is an attempt to fix apps retuning 404 when trying to access from mission control
> fix: Change environment variable from NODE_ENV to EVMOS_APP_ENV

- apps/assets/src/components/asset/modals/transactions/hooks/useDeposit.ts
- apps/assets/src/components/asset/modals/transactions/hooks/useWithdraw.ts
- apps/governance/src/components/governance/modals/hooks/useVote.tsx
- apps/staking/src/components/staking/modals/hooks/useCancelUndelegations.tsx
- apps/staking/src/components/staking/modals/hooks/useDelegation.tsx
- apps/staking/src/components/staking/modals/hooks/useRedelegation.tsx
- apps/staking/src/components/staking/modals/hooks/useRewards.tsx
- apps/staking/src/components/staking/modals/hooks/useUndelegations.tsx
- package.json
- packages/tracker/src/constants.ts
- packages/tracker/src/index.tsx
- packages/tracker/src/useTracker.tsx
- Add new metrics: un/successful transactions for deposit, withdraw, vote, delegate, undelegate, cancel undelegation, redelegate, claim rewards. https://www.notion.so/Events-to-Track-with-Mixpanel-fa70b600c5604f84a6840a0baf91910b#2c376b4fb98a4dd9925d761315ea5b62
- Fix error `TypeError: cannot read properties of undefined (reading 'token')`. It was appearing if the token was not set.
> feat: add tracker for un/successful transactions 

- packages/tracker/src/useTracker.tsx
Mixpanel was not working because it was trying to find the property get_config instead of config.
> fix: check for config instead of get_config property

- CHANGELOG.md
- apps/assets/package.json
- apps/assets/src/components/asset/table/AssetsTable.tsx
- apps/governance/package.json
- apps/governance/src/components/governance/Content.tsx
- apps/mission/package.json
- apps/mission/src/components/mission/Content.tsx
- apps/staking/package.json
- apps/staking/src/components/staking/Content.tsx
- packages/ui-helpers/package.json
- packages/ui-helpers/src/SystemErrorBanner.tsx
- packages/ui-helpers/src/index.tsx
This PR adds a simple system error banner to inform users Ledger + Keplr is currently not working.
The banner has been added to all apps
Example:
> chore: Add system error banner for ledger + keplr

- apps/vesting/src/components/vesting/header/CreateAccountModal.tsx
- apps/vesting/src/components/vesting/header/Header.tsx
- apps/vesting/src/components/vesting/header/helpers.spec.tsx
- apps/vesting/src/components/vesting/header/helpers.ts
- package.json
- yarn.lock
Create the modal for creating new vesting accounts
- Default option: Team
- Vesting duration, cliff, schedule and lockup are disabled if Team or Grantee are selected.
- When you select a date, it will show the end date (it adds the duration vesting value to the date selected) 
- The address has to start with evmos or 0x (Required)
- The account name is stored in the localstorage
- The amount has to be lower or equal than the available value. (Required)
> feat: create modal for vesting accounts

- apps/vesting/src/components/vesting/Content.tsx
- apps/vesting/src/components/vesting/content/AccountDetails.tsx
- apps/vesting/src/components/vesting/content/modal/ClawbackModal.tsx
- apps/vesting/src/components/vesting/helpers.spec.tsx
- apps/vesting/src/components/vesting/helpers.ts
- apps/vesting/src/internal/fetch.ts
- apps/vesting/src/internal/helpers.ts
- apps/vesting/src/internal/hooks/useVesting.tsx
- apps/vesting/src/internal/types.ts
- packages/ui-helpers/src/ViewExplorer.tsx
This PR Implements the `v2/vesting/${account}` endpoint. 
- It displays the vesting account information in account details. For now we are just using accountAddress and funderAddress
- For the clawback modal we use:
-  accountAddress. 
- Available for clawback → unvested.amount
- Total vesting tokens → original_vesting.amount
The endpoint is returning `GET https://goapi-staging.evmos.org/v2/vesting/test net::ERR_FAILED 500` if the account is not a vesting one. 
We should check this. For now I just added a try/catch to handle it.
> feat: use vesting endpoint for account detail - clawback modal

- CHANGELOG.md
- apps/governance/package.json
- apps/governance/src/components/governance/proposalPage/vote/VoteButton.tsx
- apps/governance/src/internal/common/functionality/hooks/fetch.ts
- apps/governance/src/internal/common/functionality/hooks/types.ts
- apps/mission/src/internal/types.ts
- packages/evmos-wallet/package.json
- packages/evmos-wallet/src/index.tsx
- packages/evmos-wallet/src/internal/wallet/functionality/fetch.ts
- packages/evmos-wallet/src/internal/wallet/functionality/hooks/useEvmosBalance.ts
- packages/evmos-wallet/src/internal/wallet/functionality/types.ts
This PR move the useEvmosBalance hook to the `evmos-wallet` package to be shared in all other packagaes and apps
> chore: move useEvmosBalance to evmos-wallet

- apps/mission/src/components/copilot/steps/setUpAccount/buttons/ButtonCopilot.tsx
When the button has the status processing the user should not be able to click on it.
> fix: add disable to processing button

- apps/mission/src/components/copilot/CopilotModal.tsx
- apps/mission/src/components/copilot/steps/setUpAccount/buttons/useStep.tsx
- apps/mission/src/components/copilot/steps/setUpAccount/types.ts
- apps/mission/src/components/copilot/steps/setUpAccount/utils.ts
- apps/mission/src/components/copilot/utils.ts
Chrome and brave need to reload the page in order to know if the window.ethereum is undefined or not
https://github.com/evmos/apps/assets/40247040/61094e00-3777-4fc9-9bc4-af7baf7192ce
> fix: install Metamask in chrome/brave

- CHANGELOG.md
- packages/copilot/package.json
- packages/copilot/src/copilot/steps/topUp/Intro.tsx
- packages/copilot/src/copilot/steps/topUp/ProviderDropdown.tsx
- packages/tracker/package.json
- packages/tracker/src/constants.ts
- packages/tracker/src/index.tsx
This PR adds event tracking for when users change on-ramp providers and when users choose to onboard via cryptocurrency swap
> chore: Card provider and crypto swap topup events 

- apps/assets/src/components/topBarButtons/common/AccountInformation.tsx
- packages/ui-helpers/src/Tooltip.tsx
Fix display tooltip. It was showing the description if the user was hovering the content instead of only the icon.
Ticket
> fix: display tooltip only if the user hover above the icon

- apps/assets/next.config.mjs
- apps/assets/package.json
- apps/governance/next.config.mjs
- apps/governance/package.json
- apps/mission/next.config.mjs
- apps/mission/package.json
- apps/staking/next.config.mjs
- apps/staking/package.json
- apps/vesting/next.config.mjs
- apps/vesting/package.json
- package.json
- packages/config/next/with-config.js
- packages/config/package.json
- packages/constants-helper/package.json
- packages/copilot/package.json
- packages/evmos-wallet/package.json
- packages/helpers/package.json
- packages/icons/package.json
- packages/playwright-config-custom/package.json
- packages/services/package.json
- packages/stateful-components/package.json
- packages/tailwind-config/package.json
- packages/tracker/package.json
- packages/ui-helpers/package.json
- pnpm-lock.yaml
So yea, this error they mention is a real pain in the ass, and its due to the fact that wagmi has some global side effects. 
The issue happens because when we create a wagmi config with something like this
```tsx
export const wagmiConfig = createConfig({
autoConnect: true,
connectors: [
...(safeConnector.ready
? [safeConnector]
: [metamaskConnector, walletConnectConnector, keplrConnector]),
],
publicClient,
});
```
it creates the config in the wagmi internal scope..
the problem is that some things can lead next bundler to import duplicated copies of wagmi
The reasons for this could be as trivial as for example, evmos-wallet depends on wagmi, assets-page depends on wagmi and zod
because wagmi also depends on zod
the bundler and package manager will think "well, let's have two copies, one …
> fix: fix duplicated wagmi instances

- CHANGELOG.md
- package.json
This PR releases v1.2.2 of the dashboard
- apps/assets 1.0.27 apps/vesting 1.0.20 apps/governance 1.0.25 apps/mission 1.0.23 apps/staking 1.0.22 | Remove semicolon
- (apps/assets 1.0.26 | packages/evmos-wallet 1.0.16 | Fix erc20 convert issue
- (apps/copilot 1.0.6 | Fixing copilot wallet connection issue
> chore: release v1.2.2

- packages/ui-helpers/src/ModalWithTransitions.tsx
Add overflow-auto for modal-black 
ERROR: 
FIX: scrollable
> fix: sizing for modal-black

- apps/assets/src/components/topBarButtons/request/ReceiveContent.tsx
Use text param in share API when sharing wallet address!
> chore: use text param

- packages/evmos-wallet/src/registry-actions/get-erc20-token-balances.ts
- pnpm-lock.yaml
stride balances on evmos were wrong because there was an index offset when matching the balance to the token it referred to
Ticket #
> fix: stride is reading the wrong balance

- apps/assets/src/components/topBarButtons/transfer/TransferModalContent.tsx
Fee error messages were only being displayed when the topup button was active
now it's also showing when the Send button is active
Ticket #
> fix: display fee error message properly

- CHANGELOG.md
- apps/assets/package.json
- package.json
- pnpm-lock.yaml
Release v1.3.2
- (fix) | apps/assets 1.0.29 | fee error message was not being displayed when fee was not paid in Evmos
> chore: release v1.3.1 

- apps/assets/src/components/asset/modals/transactions/contracts/hooks/useWEVMOS.ts
- apps/assets/src/components/asset/modals/transactions/hooks/useConvert.ts
Withdrawal TX preparation does not work non-EOA accounts (aka contracts) - it shows execution reverted even though there is no reason for it to be reverted.
I checked the contract - it reverts the function if the balance is lower than the withdrawal amount. However, safe has enough of it.
Also, I performed withdrawal transaction for safe using tx-builder - [and there were no problems](https://escan.live/tx/0x71983446fe9fd11d37ce23b1e7050e34909101db738dcc3362ea4a17f5202224).
**Encoding data** and sending it via **sendTransaction** function works with no issues. 
Just in case left this logic only for safe connector, hence why connector ID is passed to the withdraw function. 
Ticket #
> Fix: withdraw for safe

- apps/vesting/public/manifest.json
- apps/vesting/src/components/vesting/header/Header.tsx
- apps/vesting/src/internal/useVestingPrecompile.ts
- packages/evmos-wallet/src/wallet/components/WalletProvider.tsx
- packages/evmos-wallet/src/wallet/wagmi/usePubKey.ts
This PR attempts to fix vesting app not working for safe. To do this we simply add a description field to the manifest.json file of the vesting application.
This PR also fixes a bug related to pubkey derivation of a connected account. We skip pubkey derivation if the connected wallet is safe
> chore: pubkey & manifest.json fixes

- CHANGELOG.md
- packages/evmos-wallet/package.json
- packages/evmos-wallet/src/registry-actions/transfers/prepare-contract-erc20-transfer.ts
- packages/evmos-wallet/src/registry-actions/transfers/prepare-contract-ibc-transfer.ts
- packages/evmos-wallet/src/registry-actions/utils/get-chain-account-info.ts
- packages/evmos-wallet/src/wallet/wagmi/keplrConnector.ts
Two issues actually
we were failing to get the public key for some accounts
also, we were not using the estimations in some contract calls
Ticket #
> fix: gas estimation wasn't being used on keplr tx

- CHANGELOG.md
- package.json
Release `v.1.3.4`
- (fix) fse-754 | packages/ui-helpers 1.0.16 | Add attribution to Coingecko
- (fix) fse-778 | apps/assets 1.0.32 packages/helpers 1.0.9 | Update Timestamp for success transactions
- (chore) fse-740 | apps/assets 1.0.31 apps/mission 1.0.24 packages/stateful-components 1.0.1 | Update head component
- (fix) fse-784 | apps/assets 1.0.30 packages/icons 1.0.7 packages/ui-helpers 1.0.15 | Transaction failure message even if successful
- (chore) | packages/playwright-config-custom 1.0.3 packages/evmos-wallet 1.0.17 packages/copilot 1.0.6 | Using Lava RPCs as default ones
- (fix) | packages/evmos-wallet 1.0.18 | Gas estimation wasn't being used in contract calls | Fixes issue with getting the public key for some accounts
> chore: release v1.3.4

- apps/mission/public/_redirects_staging
change order for assets redirect
Trying this approach: 
With the redirect rules in this order, requests to /assets will no longer be redirected to /portfolio/:splat. Instead, they will be matched by the last rule in the config file and redirected to /portfolio/:splat.
Ticket #fse-794
> change order for assets redirect

- apps/mission/public/_redirects_staging
Trying  `/assets/* https://staging-app.evmos.org/portfolio/:splat` instead of /portfolio
Ticket #fse-794
> redirect to assets app on staging

- CHANGELOG.md
- apps/assets/package.json
- apps/mission/package.json
- apps/mission/public/_redirects_prod
- packages/stateful-components/package.json
Update redirects. Use /portfolio instead of /assets for prod.
Ticket #fse-794
> chore: update redirects prod

- apps/mission/e2e/copilot.nonetwork.spec.ts
- apps/mission/e2e/copilot.spec.ts
- apps/mission/e2e/dappstore.spec.ts
- packages/copilot/src/copilot/steps/topUp/Squid.tsx
- packages/test-utils/package.json
- packages/test-utils/playwright/fixtures/metamask.ts
- packages/test-utils/playwright/utils/index.ts
- packages/test-utils/playwright/utils/page-listener.ts
- packages/testnet/package.json
- pnpm-lock.yaml
This PR solves two things
1 - update dappwright package and adapt a few things to it because it uses a newer version of metamask
2 - reduce flakiness of some tests caused by race conditions in the usage of the `waitForEvent('page')` method
Ticket #
> fix: update dappwright and some e2e tests

- CHANGELOG.md
- packages/evmos-wallet/package.json
- packages/evmos-wallet/src/registry-actions/transfers/prepare-contract-ibc-transfer.ts
Simulated estimations are wrong so we're hardcoding gas limit for now
Example transaction that's failed: https://escan.live/address/0x0000000000000000000000000000000000000802
This is due to a bug on gas estimations in core
Follow discussion here: 
https://altiplanic.slack.com/archives/C0541U45A1K/p1698861111074019
The long fix will come with the fix from Core (see ticket from our side here [FSE-797](https://linear.app/altiplanic/issue/FSE-797/convert-button-not-working-for-mm-fine-with-keplr))
Ticket FSE-835
> fix: hardcode estimation for ics transfers

- CHANGELOG.md
- apps/assets/src/components/asset/modals/transactions/contracts/hooks/useWEVMOS.ts
- packages/evmos-wallet/package.json
- pnpm-lock.yaml
The `wagmi` prepareTransaction function seems not to be compatible with safe.
This PR removes the prepareTransaction step for unwrapping WEVMOS and directly executes the sendTransaction function call which seems to be compatible with safe
> chore: Fix Safe WEVMOS unwrap

- CHANGELOG.md
- package.json
- (chore) fse-815 | apps/assets 1.0.41 packages/evmos-wallet 1.0.24 packages/registry 1.0.4 | Enable Kujira network
- (chore) fse-864 | packages/evmos-wallet 1.0.24 | remove prepareTransaction for unwrapping wevmos
- (chore) fse-846 | apps/assets 1.0.40 apps/mission 1.0.27 packages/constants-helper 1.0.10 packages/tracker 1.0.9 packages/ui-helpers 1.0.20 | Get rid of broken links and create a reusable link component
- (chore) fse-819 | packages/constants-helper 1.0.9 packages/icons 1.0.11 packages/ui-helpers 1.0.19 | Add medium to footer
- (fix) fse-802 | packages/ui-helpers 1.0.18 | Center text in staking app
- (chore) fse-799 | packages/copilot 1.0.10 | Use wagmi value instead of redux value
- (fix) fse-816 | packages/ui-helpers 1.0.17 packages/icons 1.0.10 | Replace Twitter logo to X …
> Release v1.3.9

- pages/dappstore/src/pages/dapp-explorer/partials/explorer-breadcrumbs.tsx
redirect to /dapps when user clicks on dappstore (breadcrumbs)
Ticket #fse-866
> fix: redirect on breadcrumbs

- apps/mission/src/components/header/Header.tsx
- apps/mission/src/components/header/LaunchPad.tsx
- packages/constants-helper/src/constants.ts
- packages/constants-helper/src/index.ts
- packages/i18n/locales/en/common.json
- packages/i18n/locales/en/copilot-setup-account.json
- packages/i18n/locales/en/dappStore.json
- packages/ui-helpers/src/launchPad/Container.tsx
- pages/dappstore/src/pages/dapp-explorer/dapp-explorer-page.tsx
- pages/dappstore/src/pages/dapp-explorer/partials/header-categories.tsx
- pages/dappstore/src/pages/landing/partials/ecosystem-card.tsx
- pages/dappstore/src/pages/landing/partials/ecosystem-section.tsx
- pages/dappstore/src/pages/landing/partials/hero-section.tsx
- pnpm-lock.yaml
Fixes: bug from deploy preview
- Styles
- "View all dApps" in the nav bar / app launcher should NOT lead to a new tab, it should update the page the user is on already
- Fix: 
- "Setup up your account" to "Set up your account"
- "Topup your account" to "Top up your account"
- Link leads to: https://deploy-preview-689--evmos-mission.netlify.app/docs, 404 error, maybe this wasn't intended
- Sort Instant dApps in home page according to the order listed in [FSE-852](https://linear.app/altiplanic/issue/FSE-852/page-1-home-page) (see Acceptance Criteria)
- rename to "Home"
- font size of the dApp name could be a bit bigger, without making changes to the font size for "Instant dApp"
Ticket #fse-877
> fixes: bug from deploy preview

- pages/dappstore/src/pages/landing/partials/copilot-card/copilot-card.tsx
The let's go and top-up buttons inside copilot card weren't working. 
We'll use sendEvent instead of TrackerEvent. With that change the modal appears and the event is tracked. 
Ticket #
> fix: copilot card buttons

- pages/dappstore/src/pages/dapp-explorer/partials/header-categories.tsx
show correct amount of dapps on instant dapp explorer
Ticket #fse-909
> fix: amount of dapps showing on instant dapp explorer

- packages/instant-dapps/src/dapps/Osmosis.tsx
- packages/instant-dapps/src/dapps/Stride.tsx
- packages/widgets/src/Osmosis/Osmosis.tsx
Show value instead of NaN on osmosis. 
Update colors
Add pulse animation for images when tokenIdentifier is not set.
Ticket #fse-915 and #fse-916
> fix: show value instead of NaN on osmosis. Update colors

- packages/widgets/src/Osmosis/Osmosis.tsx
Fix: putting in an input greater than 80 in the osmosis widget
We were using `formatUnits` from viem and we had to import if from `@ethersproject/units`
Also it was crashing because the number was too big, and it was sent as ...e21
Ticket #fse-922
> fix: putting in an input greater than 80 in the osmosis widget

- packages/widgets/src/Osmosis/Osmosis.tsx
Disable swap button if amount is 0. 
Allow entering 0.01 as a value
Ticket #
> fix: osmosis widget display values

- packages/widgets/src/Osmosis/Osmosis.tsx
Update: use 6 decimals instead of 3 on osmosis widget
Ticket #fse-942
> fix: use 6 decimals instead of 3 on osmosis widget

- apps/mission/src/components/header/LaunchPad.tsx
Close launchpad after clicking on view all dapps. It was missing the close prop
Ticket #fse-947
> fix: close launchpad after clicking on view all dapps

- packages/instant-dapps/src/dapps/instant-dapp-container.tsx
Fix: blur widget until is connected. Use isConnected instead of isDisconnected
Ticket #fse-943
> fix: blur widget until is connected

- packages/stateful-components/src/modals/ConnectModal/ConnectModalContent.tsx
- packages/ui-helpers/src/Modal.tsx
- packages/ui-helpers/src/modal/Introduction.tsx
add x on connection modal
fix size images for EvmosRedIcon
Ticket #fse-946
> fix: add x on connection modal and fix size images for EvmosRedIcon

- CHANGELOG.md
- package.json
- packages/helpers/package.json
- (fix) packages/helpers 1.0.12 | Adds absolute url to rpcs on wagmi config
> Release 2.0.1

- CHANGELOG.md
- pages/portfolio/package.json
- pages/portfolio/src/modals/common/AmountBox.tsx
- pages/portfolio/src/modals/pay/Content.tsx
Images in pay modal were not showing correctly.
Add lowercase to fix the issue
Ticket #fse-960
> fix: pay modal images to lowercase

- CHANGELOG.md
- package.json
- pages/portfolio/package.json
- pages/portfolio/src/asset/table/ContentTable.tsx
- pages/portfolio/src/asset/table/components/SubRowContent.tsx
- pages/portfolio/src/asset/table/components/subrow-content.spec.tsx
- pages/portfolio/src/asset/table/components/types.ts
Delete the WEVMOS row from the balance table and continue with the modifications to implement single token representation.
- A filter was created that when listing the balance, filters the EVMOS erc20 values ​​so as not to save them in the array shown on the screen.
- Modifications were made to the table to avoid conflicts with the variables.
- The values ​​associated with WEVMOS were removed from the subrow.
⚠️ The website was adapted to receive the new balances, so until the modifications are made in the backend, some balances may not give correct values.
> fix: remove wevmos row

- CHANGELOG.md
- pages/portfolio/package.json
- pages/portfolio/src/asset/table/components/SubRowContent.tsx
Subbalances that appear on the sublines of each token have been removed.
ISC20 balances were removed instead of ERC20 as indicated in the task, as the core team was consulted and it was recommended to make this change.
While all references to balances of type cosmos could be removed, the overall balance in the [ContentTable.tsx](https://github.com/evmos/apps/blob/main/pages/portfolio/src/asset/table/ContentTable.tsx) component was not modified so as not to interfere with other tickets.
Ticket #
> fix: remove double balance

- CHANGELOG.md
- pages/dappstore/package.json
- pages/dappstore/src/pages/landing/partials/ecosystem-section.tsx
limit of highlighted dapps to 8 not 9
Ticket #dapp-58
> limit of highlighted dapps to 8 not 9

- CHANGELOG.md
- packages/widgets/package.json
- packages/widgets/src/forge.tsx
This PR simply updates the Forge widget router URL to the new deployment managed by the evmos infra team
> chore: update forge widget router URL

- apps/mission/src/components/header/edit/ModalEdit.tsx
Display hex address if user didn't ser profile name
Ticket #dapp-77
> fix: display name should be the user address

- pages/dappstore/src/pages/landing/partials/ecosystem-card.tsx
fix: use thumbnail instead of cover for ecosystem card
Ticket #dapp-115
> use thumbnail instead of cover for ecosystem card

- apps/mission/src/components/header/signin/ManageProfileModal.tsx
- apps/mission/src/components/useSignInWithEthereum.tsx
- apps/mission/src/components/warning/mismatch-address.tsx
Add logic for mismatch addresses. 
When you change the address on your wallet extension, it will appear in the ui an alert saying that the addresses from the profile and extension doesn't match. 
If you click on manage profile it will appear a modal with the option to sign in with the address that is on your wallet extension.
Cases that were tested:
- Coinbase
- Metamask
- Keplr
- Trust
- Rabby
Ticket #dapp-182
> feat: add logic for mismatch addresses
