evmos/apps

apps/assets/README.md
This PR updates the assets app readme with information on how to add/register new chains/tokens using the CTR
=> update assets readme

CHANGELOG.md, turbo.json
I added the dependencies order so that the dev pipeline runs in the right order
=> Bug: Fixing issue with yarn dev

package.json
Hot fix for fixing corrupted package.json file
=> chore: fix package.json file

CHANGELOG.md, package.json, packages/constants-helper/src/constants.ts, packages/evmos-wallet/package.json, packages/evmos-wallet/src/internal/wallet/functionality/networkConfig.ts, turbo.json
This PR add the NEXT_PUBLIC_ prefix to all env vars used by the app
=> chore: Add env vars prefix

CHANGELOG.md, clear-cache.sh, package.json, turbo.json
- Addind script to clear cache
- Disabled cache for the build as suggested by @miliPaoletti
=> fix: adding clear cache script

CHANGELOG.md, apps/assets/package.json, apps/assets/src/components/asset/table/AssetsTable.tsx, apps/governance/package.json, apps/governance/src/components/governance/Content.tsx, apps/mission/package.json, apps/mission/src/components/mission/Content.tsx, apps/staking/package.json, apps/staking/src/components/staking/Content.tsx, package.json, packages/ui-helpers/package.json, packages/ui-helpers/src/SystemErrorBanner.tsx, packages/ui-helpers/src/index.tsx
This PR is for releasing `v1.0.8`
=> chore: release v1.0.8

apps/vesting/src/components/vesting/Content.tsx, apps/vesting/src/components/vesting/header/Header.tsx, apps/vesting/src/components/vesting/header/SearchVesting.tsx, packages/ui-helpers/src/Search.tsx, packages/ui-helpers/src/index.tsx
Add header for vesting:
- Add search component for searching accounts.
- TODO: add the routing logic when the user clicks on the search icon or press enter.
- Add Creating vesting account button. 
- TODO: add the modal when the user clicks on the button
- Add message for listing vesting accounts
=> feat: create header for vesting

apps/vesting/src/components/vesting/Content.tsx, apps/vesting/src/components/vesting/content/AccountDetails.tsx, packages/constants-helper/src/constants.ts, packages/constants-helper/src/index.ts
Add vesting account details with dummy information
=> feat: add vesting account details

CHANGELOG.md, package.json
=> chore: release v1.0.9

apps/vesting/src/components/vesting/Content.tsx, apps/vesting/src/components/vesting/content/AccountDetails.tsx, apps/vesting/src/components/vesting/content/modal/ClawbackModal.tsx, apps/vesting/src/components/vesting/content/modal/ItemModal.tsx, packages/evmos-wallet/src/notification/Snackbar.tsx, packages/icons/src/ExclamationIcon.tsx, packages/icons/src/index.tsx
Add modal for clawback.
TODO
- handle clawback action
- format totalTokens and availableClawback depending on the response
Update: add warning icon
=> feat: add modal for clawback

CHANGELOG.md, apps/assets/package.json, apps/assets/pages/index.tsx, apps/governance/package.json, apps/governance/pages/index.tsx, apps/mission/package.json, apps/mission/pages/index.tsx, apps/staking/package.json, apps/staking/pages/index.tsx, package.json
Release 1.0.10.
This release basically removes the Hackathon information banner
=> chore: release v1.0.10

apps/vesting/src/components/vesting/content/AccountDetails.tsx, apps/vesting/src/components/vesting/header/Header.tsx, packages/evmos-wallet/src/wallet/ButtonWalletConnection.tsx
For v0 we are going to support MM and Wallet Connect. We disable the clawback and create vesting account if the provider is Keplr.
=> feat: disable Keplr if it is vesting app

apps/vesting/src/components/vesting/content/AccountDetails.tsx, apps/vesting/src/components/vesting/header/CreateAccountModal.tsx, apps/vesting/src/components/vesting/helpers.ts
It was only storing the account name but we want to store multiples accounts names. For that we need to store the address too.
=> fix: store address and account name while creating the new account

apps/vesting/src/components/vesting/header/CreateAccountModal.tsx
=> fix: align selects

CHANGELOG.md, apps/assets/package.json, apps/assets/src/__mocks__/mixpanel-browser.ts, apps/assets/src/components/asset/modals/transactions/Convert.tsx, apps/assets/src/components/asset/table/components/SubRowContent.tsx, packages/tracker/src/constants.ts, packages/tracker/src/index.tsx, vitest.workspace.ts
This PR adds convert button for Gravity assets just like we have for Axelar assets
=> chore: add convert button for gravity assets

CHANGELOG.md, package.json
=> Release v1.0.11

apps/assets/src/components/asset/dropdown/DropdownTokens.tsx, apps/governance/pages/globals.css
- Add style for lists in markdown
- Update mixpanel property for Dropdown tokens. The first click was not working correctly (it was undefined).
=> fix: styles and metrics

CHANGELOG.md, package.json
=> chore: release v1.0.12

CHANGELOG.md, apps/governance/e2e/flow.spec.ts, packages/evmos-wallet/package.json, packages/evmos-wallet/src/locales/en.ts, packages/evmos-wallet/src/locales/translate.ts, packages/evmos-wallet/src/wallet/ButtonWalletConnection.tsx, yarn.lock
- Added https://github.com/schummar/schummar-translate for i18n to the evmos-wallet library
=> feat: i18n support for packages

CHANGELOG.md, apps/governance/e2e/flow.spec.ts, apps/mission/src/components/copilot/steps/setUpAccount/SetUpAccountContainer.tsx, apps/mission/src/components/mission/StatefulHeader.tsx, apps/mission/src/components/mission/copilot/CancelModal.tsx, packages/evmos-wallet/package.json, packages/evmos-wallet/src/locales/en.ts, packages/evmos-wallet/src/locales/translate.ts, packages/evmos-wallet/src/wallet/ButtonWalletConnection.tsx, packages/icons/src/AlertIcon.tsx, packages/icons/src/index.tsx, yarn.lock
Create the the cancel modal component for the copilot. It just the component
=> chore: cancel modal

apps/mission/public/locales/en/common.json, apps/mission/src/components/copilot/CopilotModal.tsx, apps/mission/src/components/copilot/container/StepsContainer.tsx, apps/mission/src/components/copilot/container/StepsContext.tsx, apps/mission/src/components/copilot/container/data.tsx, apps/mission/src/components/copilot/container/helpers.tsx, apps/mission/src/components/copilot/steps/nextSteps/NextSteps.tsx, apps/mission/src/components/copilot/steps/nextSteps/helpers.tsx, apps/mission/src/components/copilot/steps/setUpAccount/SuccessSetUp.tsx, apps/mission/src/components/copilot/steps/setUpAccount/buttons/ButtonCopilot.tsx, apps/mission/src/components/copilot/steps/setUpAccount/buttons/utils.ts, apps/mission/src/components/copilot/steps/setUpAccount/utils.ts, apps/mission/src/components/copilot/steps/topUp/Onboard.tsx, apps/mission/src/components/copilot/steps/topUp/SuccessTopUp.tsx, apps/mission/src/components/copilot/useCopilot.tsx, apps/mission/src/components/mission/StatefulHeader.tsx, packages/icons/src/CreditCards.tsx, packages/icons/src/Ethereum.tsx
Create a useContext for managing the state of the stepper. When the user clicks on a button, we should add the logic to update the context there. 
https://github.com/evmos/apps/assets/40247040/7ad84950-4da3-4116-ace2-b4118f0a9112
=> feat: add steps logic for copilot components

CHANGELOG.md, package.json
=> chore: release v1.0.14

apps/mission/e2e/copilot.spec.ts
Testing copilot flow: Click on `Connect` and then in `Evmos Copilot Recommended for first time users` instead of clicking on copilot
=> fix: update e2e test

package.json
Changing concurrency setting to make the e2e test work
=> fix: updating config to fix e2e tests

packages/copilot/src/copilot/steps/icons/ConfettiEmoji.tsx, packages/copilot/src/copilot/steps/icons/HandsEmoji.tsx, packages/copilot/src/copilot/steps/nextSteps/NextSteps.tsx, packages/copilot/src/copilot/steps/setUpAccount/SuccessSetUp.tsx, packages/copilot/src/copilot/steps/setUpAccount/buttons/ButtonCopilot.tsx, packages/copilot/src/copilot/steps/topUp/SuccessTopUp.tsx, packages/tailwind-config/tailwind.config.js
Create reusable component for confetti and hands emoji
=> chore: create components for emojis

CHANGELOG.md, apps/assets/package.json, apps/governance/package.json, apps/mission/package.json, apps/staking/package.json, apps/vesting/package.json, package.json, packages/evmos-wallet/package.json, packages/tailwind-config/package.json, packages/ui-helpers/package.json
This PR releases version 1.1.0
=> Release v1.1.0

CHANGELOG.md, packages/copilot/package.json, packages/copilot/src/copilot/steps/topUp/Transak.tsx
We were using staging url instead of prod
=> fix: transak url

CHANGELOG.md, package.json
=> Release v1.1.3

apps/governance/src/internal/governance/functionality/hooks/useProposals.ts
https://altiplanic.slack.com/archives/C0544L9AQBG/p1691012012687339
=> chore: remove proposal number 156

CHANGELOG.md, apps/governance/package.json, package.json
=> Release v1.1.4

apps/mission/src/components/mission/apps/Header.tsx, apps/mission/src/components/mission/dappStore/constants.ts, apps/mission/src/components/mission/dappStore/ecosystem/Container.tsx, packages/constants-helper/src/constants.ts, packages/constants-helper/src/index.ts
Remove the constants file from Mission Control and add the urls in the constants helper package
=> feat: add google form url to constants-helper package

packages/ui-helpers/src/PingIndicator.tsx, packages/ui-helpers/src/launchPad/Container.tsx
Add pulse animation to the launcher dapp
=> feat: add pulse animation

apps/assets/src/components/asset/table/AssetsTable.tsx, apps/governance/src/components/governance/Content.tsx, apps/staking/src/components/staking/Content.tsx, packages/evmos-wallet/src/copilot/utils.tsx, packages/evmos-wallet/src/wallet/buttons/Button.Profile.tsx, packages/icons/src/KeplrIcon.tsx, packages/icons/src/MetamaskIcon.tsx, packages/icons/src/WalletConnectIcon.tsx, packages/ui-helpers/src/launchPad/Container.tsx
Small UI Fixes for the following:
- Replace DApps with dApps
-   https://linear.app/altiplanic/issue/FSE-730/replace-dapps-to-dapps
- Align navbar elements
-   https://linear.app/altiplanic/issue/FSE-731/change-style-of-apps-in-evmos-apps
- Remove back to mission control button
-   https://linear.app/altiplanic/issue/FSE-729/remove-all-the-back-to-in-apps
=> chore: UI bug fixes

CHANGELOG.md, package.json
=> chore: Release v1.2.0

.github/pull_request_template.md, CHANGELOG.md
=> ci: adding PR review template

CHANGELOG.md, apps/assets/package.json, apps/assets/src/internal/asset/functionality/transactions/convert.ts, packages/evmos-wallet/package.json, packages/evmos-wallet/src/api/apiConvertCoin.ts
Some arguments were swapped in the wallet refactor
Ticket #
=> fix: fix erc20 convert issue

CHANGELOG.md, packages/copilot/package.json, packages/copilot/src/copilot/steps/setUpAccount/utils.ts, packages/evmos-wallet/src/wallet/components/WalletProvider.tsx, pnpm-lock.yaml
Fixing a wallet connection issue by adjusting how the 'copilot' package  to call the new method for connecting through wagmi
Ticket #
=> fix: fixes copilot wallet connection issue

apps/assets/src/components/topBarButtons/parts/AccountSelector.tsx, packages/ui-helpers/src/crypto-selector/CryptoSelector.tsx, packages/ui-helpers/src/modal/tabs/Tabs.tsx
Add last styles for dropdown. 
Add mobile styles for tabs in `To` section
=> add styles for dropdown

CHANGELOG.md, apps/assets/package.json, package.json
This PR releases support for NEOK token in the assets page
=> Release v1.2.3

apps/assets/public/locales/en/common.json, apps/assets/src/components/topBarButtons/parts/AssetSelector.tsx, apps/assets/src/components/topBarButtons/transfer/Content.tsx, packages/config/tailwind/base.js, packages/ui-helpers/src/AmountInput.tsx, packages/ui-helpers/src/ErrorMessage.tsx
Add errors below input for send modal. 
=> add errors below input

apps/assets/public/locales/en/common.json, apps/assets/src/components/topBarButtons/shared/AccountSelector.tsx, apps/assets/src/components/topBarButtons/shared/AssetSelector.tsx, apps/assets/src/components/topBarButtons/shared/TransferSummary.tsx, apps/assets/src/components/topBarButtons/transfer/TransferModalContent.tsx, packages/config/tailwind/base.js, packages/ui-helpers/src/AmountInput.tsx, packages/ui-helpers/src/ErrorMessage.tsx, packages/ui-helpers/src/InfoPanel.tsx, packages/ui-helpers/src/crypto-selector/CryptoSelector.tsx, packages/ui-helpers/src/crypto-selector/CryptoSelectorBalanceBox.tsx, packages/ui-helpers/src/crypto-selector/CryptoSelectorBalanceText.tsx, packages/ui-helpers/src/crypto-selector/CryptoSelectorBox.tsx, packages/ui-helpers/src/crypto-selector/CryptoSelectorTitle.tsx, packages/ui-helpers/src/inputs/TextInput.tsx, packages/ui-helpers/src/labels/Label.tsx, packages/ui-helpers/src/modal/Subtitle.tsx, packages/ui-helpers/src/modal/Title.tsx, packages/ui-helpers/src/modal/tabs/Tabs.tsx, packages/ui-helpers/src/transfer-confirmation/ConfirmationMessage.tsx, packages/ui-helpers/src/transfer-confirmation/ConfirmationTitle.tsx, packages/ui-helpers/src/transfer-confirmation/ContainerItem.tsx
- Add error message as info if in the to section the network is only evmos.
- Update styles for mobile version
- Show `error getting balance. Please connect...` when the user enters to the modal before connecting.
=> feat: add mobile styles

apps/assets/src/components/topBarButtons/transfer/TransferModalContent.tsx, packages/evmos-wallet/src/copilot/utils.tsx
- Show transfer summary correctly
- Change format for insufficient fee balance. Instead of formattedLong changed to formatted
=> show transfer summary correctly

apps/assets/package.json, apps/assets/src/components/topBarButtons/pay/Content.tsx, apps/assets/src/components/topBarButtons/pay/Modal.tsx, apps/assets/src/components/topBarButtons/request/Content.tsx, apps/assets/src/components/topBarButtons/request/ReceiveContent.tsx, apps/assets/src/components/topBarButtons/request/RequestAssetSelector.tsx, apps/assets/src/components/topBarButtons/request/RequestModal.tsx, apps/assets/src/components/topBarButtons/request/SetupContent.tsx, apps/assets/src/components/topBarButtons/request/ShareContent.tsx, apps/assets/src/components/topBarButtons/shared/AssetSelector.tsx, pnpm-lock.yaml
- Updates components with latest versions and new helpers
- Resolves conflicts
- Adds QR codes
=> update from base branch and added QR codes

apps/assets/pages/globals.css, apps/assets/src/components/topBarButtons/pay/Content.tsx, apps/assets/src/components/topBarButtons/transfer/TransferModalContent.tsx, packages/ui-helpers/src/index.tsx, packages/ui-helpers/src/spinners/Spinner.tsx
- Add spinner component and use it in send / pay buttons
=> add spinner component

apps/assets/src/components/asset/table/topBar/TopBar.tsx, apps/assets/src/components/topBarButtons/transfer/TransferModal.tsx, packages/ui-helpers/src/PrimaryButton.tsx, packages/ui-helpers/src/spinners/Spinner.tsx
- fix styles for CTA buttons.
- update styles for spinner
=> fix: styles CTA buttons

apps/assets/public/locales/en/common.json
Fix: change word wallet for account
=> fix: change wallet for account

apps/assets/src/components/topBarButtons/request/ReceiveContent.tsx, apps/assets/src/components/topBarButtons/request/RequestAssetSelector.tsx, apps/assets/src/components/topBarButtons/request/SetupContent.tsx, apps/assets/src/components/topBarButtons/request/ShareContent.tsx, apps/assets/src/components/topBarButtons/shared/AssetSelector.tsx, apps/assets/src/components/topBarButtons/transfer/TransferModalContent.tsx
For pay/request flows: show `connect` button if the user enters to a modal and they are not connected.
Ticket #
=> add connect button for pay/request flows

apps/assets/public/manifest.json, apps/mission/public/manifest.json
Updating manifest.json description for EVM supported apps so they would appear in custom app section (localhost).
=> chore: update manifest.json description for safe apps

apps/assets/public/locales/en/common.json, apps/assets/src/components/topBarButtons/pay/Content.tsx, apps/assets/src/components/topBarButtons/transfer/TransferModalContent.tsx
Add try again text and message error while transferring. For example the user clicks on send and they close the popup 
=> add try again and message error while transferring

packages/config/next/with-config.js
=> allow safe to load the dashboard within an iframe

apps/assets/src/components/topBarButtons/receipt/ReceiptModalContent.tsx, apps/assets/src/components/topBarButtons/request/RequestAssetSelector.tsx, apps/assets/src/components/topBarButtons/shared/sortedChains.tsx, packages/evmos-wallet/src/registry-actions/get-erc20-token-balances.ts, packages/evmos-wallet/src/registry-actions/transfers/prepare-contract-erc20-transfer.ts, packages/registry/scripts/gen-chains.ts, packages/registry/src/chains/axelar.ts, packages/registry/src/chains/comdex.ts, packages/registry/src/chains/cosmos.ts, packages/registry/src/chains/cre.ts, packages/registry/src/chains/emoney.ts, packages/registry/src/chains/evmos.ts, packages/registry/src/chains/gravity.ts, packages/registry/src/chains/inj.ts, packages/registry/src/chains/juno.ts, packages/registry/src/chains/kava.ts, packages/registry/src/chains/osmo.ts, packages/registry/src/chains/quick.ts, packages/registry/src/chains/regen.ts, packages/registry/src/chains/stars.ts, packages/registry/src/chains/stride.ts, packages/registry/src/chains/tori.ts
That fixes the issue of Kava not having registered their fee token
Ticket #
=> feat: support networks that don't have their fee token registered

apps/assets/src/components/topBarButtons/request/ReceiveContent.tsx
Fix: 0x display format for Kava
Ticket #
=> fix: add 0x display format for Kava

CHANGELOG.md, package.json
=> chore: release 1.3.0

CHANGELOG.md, package.json
Release v1.3.1
- (fix) | 1.3.1 fix stride balance in send modal
=> chore: release v1.3.1

packages/evmos-wallet/src/api/cosmos-rest/api-cosmos-account-by-address.ts, packages/evmos-wallet/src/registry-actions/utils/get-chain-account-info.ts
=> fix: tries to get pubkey from vesting accounts

packages/ui-helpers/src/ModalWithTransitions.tsx
=> fix: fix scrolling on modals on ios

packages/ui-helpers/src/ModalWithTransitions.tsx, pnpm-lock.yaml
The last pr to fix the scroll issue introduced an error in the selectors, this fixes that
Ticket #
=> fix: scroll issue on modals

apps/assets/src/components/asset/modals/transactions/contracts/hooks/useWEVMOS.ts, apps/assets/src/components/asset/modals/transactions/hooks/useConvert.ts, apps/assets/src/components/topBarButtons/pay/Content.tsx, apps/assets/src/components/topBarButtons/receipt/ReceiptModal.tsx, apps/assets/src/components/topBarButtons/transfer/TransferModalContent.tsx, packages/evmos-wallet/src/api/useAssets.ts, packages/evmos-wallet/src/registry-actions/transfers/prepare-evm-transfer.ts, pnpm-lock.yaml
This merges Marta's changes and adapt them a little bit
Ticket #
=> feat: enable safe wallet

packages/evmos-wallet/src/wallet/wagmi/chains.ts, packages/registry/scripts/gen-chains.ts, packages/registry/scripts/lava-urls.ts, packages/registry/src/chains/axelar.ts, packages/registry/src/chains/comdex.ts, packages/registry/src/chains/cosmos.ts, packages/registry/src/chains/cre.ts, packages/registry/src/chains/emoney.ts, packages/registry/src/chains/evmos.ts, packages/registry/src/chains/gravity.ts, packages/registry/src/chains/inj.ts, packages/registry/src/chains/juno.ts, packages/registry/src/chains/kava.ts, packages/registry/src/chains/osmo.ts, packages/registry/src/chains/quick.ts, packages/registry/src/chains/regen.ts, packages/registry/src/chains/stars.ts, packages/registry/src/chains/stride.ts, packages/registry/src/chains/tori.ts, packages/registry/src/index.ts
=> feat: setup lava endpoints

apps/vesting/src/components/vesting/helpers.ts
There was a broken test on vesting helper for date parsing, this fixes that
Ticket #
=> fix: fix unit test error

CHANGELOG.md, package.json
- (fix) | fix scrolling issue on iOS modals
- (chore) | apps/vesting 1.1.0 | vesting mainnet app
=> chore: release v1.3.3

packages/evmos-wallet/src/registry-actions/transfers/prepare-cosmos-ibc-transfer.ts, packages/evmos-wallet/src/registry-actions/transfers/prepare-transfer.ts, packages/evmos-wallet/src/registry-actions/utils/create-protobuf-transaction.ts, packages/evmos-wallet/src/registry-actions/utils/getTxTimeout.ts
We didn't support nano ledger tx in this new version
Ticket #
=> feat: support for amino tx for nano ledgers

CONTRIBUTING.md, README.md, apps/assets/README.md, apps/governance/README.md, apps/mission/README.md, apps/staking/README.md
Update: change yarn forn pnpm
Ticket #fse-736
=> update: change yarn forn pnpm

apps/governance/src/internal/governance/functionality/hooks/useProposals.ts, apps/governance/src/internal/governance/functionality/types.ts
This PR updates the governance app to use the new governance v1 proposal fields in order to adequately display proposals titles and summaries
=> chore: update governace app to use new proposals fields

packages/evmos-wallet/src/registry-actions/transfers/prepare-contract-ibc-transfer.ts
=> chore: removes unnecessary console.log

apps/governance/src/internal/governance/functionality/hooks/useProposals.ts
Handle both v1 and v1beta1 proposals payload in the client
=> chore: handle v1 and v1beta prop versions

packages/icons/src/PriceDown.tsx, packages/icons/src/PriceUp.tsx
=> fix: svg props

apps/staking/src/components/staking/modals/hooks/useCancelUndelegations.tsx, apps/staking/src/components/staking/modals/hooks/useDelegation.tsx, apps/staking/src/components/staking/modals/hooks/useRedelegation.tsx, apps/staking/src/components/staking/modals/hooks/useUndelegations.tsx, packages/constants-helper/src/constants.ts, packages/constants-helper/src/index.ts, pnpm-lock.yaml
update explorer url to escan instead of mitscan in staking actions
Ticket #fse-741
=> chore: update explorer url to escan instead of mitscan

CHANGELOG.md, packages/evmos-wallet/package.json, packages/evmos-wallet/src/api/useAssets.ts, pnpm-lock.yaml
Fix EVMOS price change displaying as NaN when app is loading
=> chore: Fix NaN price change

apps/mission/e2e/copilot.spec.ts, packages/copilot/src/__tests__/TopUp.WithMixpanelToken.spec.tsx, packages/copilot/src/__tests__/TopUp.WithoutMixpanelToken.spec.tsx, packages/copilot/src/copilot/steps/topUp/Squid.tsx, packages/copilot/src/copilot/steps/topUp/TopUp.tsx, packages/copilot/src/copilot/steps/topUp/utils.tsx
- Default evmos token in squid. 
- Change Cypher name.
- Update changelog and packages
Ticket #fse-795
=> chore: update cryptocurrencies options

packages/registry/scripts/lava-urls.ts, packages/registry/src/chains/osmosis.ts
=> fix: temporarily disable osmosis lava endpoint

CHANGELOG.md, package.json, packages/registry/package.json
=> v1.3.6 release

apps/assets/next.config.mjs, apps/mission/public/_redirects_staging
=> replace assets with portfolio

apps/assets/e2e/receive-modal.spec.ts, apps/assets/e2e/send-modal.spec.ts, apps/assets/src/components/asset/HeadComponent.tsx, apps/assets/src/components/asset/dropdown/DropdownChainDeposit.tsx, apps/assets/src/components/asset/dropdown/DropdownChains.tsx, apps/assets/src/components/asset/dropdown/DropdownTokens.tsx, apps/assets/src/components/asset/dropdown/DropdownTokensDeposit.tsx, apps/assets/src/components/asset/modals/common/deposit/DepositReceiver.tsx, apps/assets/src/components/asset/modals/common/withdraw/FromWithdraw.tsx, apps/assets/src/components/asset/modals/transactions/AddTokenMetamask.tsx, apps/assets/src/components/asset/modals/transactions/Convert.tsx, apps/assets/src/components/asset/modals/transactions/ConvertSTR.tsx, apps/assets/src/components/asset/modals/transactions/Deposit.tsx, apps/assets/src/components/asset/modals/transactions/Withdraw.tsx, apps/assets/src/components/asset/table/ContentTable.tsx, apps/assets/src/components/asset/table/components/Description.tsx, apps/assets/src/components/topBarButtons/common/AmountBox.tsx, apps/assets/src/components/topBarButtons/pay/Content.tsx, apps/assets/src/components/topBarButtons/request/ReceiveContent.tsx, apps/assets/src/components/topBarButtons/request/RequestAssetSelector.tsx, apps/assets/src/components/topBarButtons/request/ShareContent.tsx, apps/assets/src/components/topBarButtons/shared/AccountSelector.tsx, apps/assets/src/components/topBarButtons/shared/AssetSelector.tsx, apps/assets/src/components/topBarButtons/shared/TransferSummary.tsx, apps/mission/e2e/dappstore.spec.ts, apps/mission/public/_redirects_staging, apps/mission/public/locales/en/common.json, apps/mission/src/components/mission/dappStore/assets/Card.tsx, packages/stateful-components/src/launchPad/dApps.tsx
redirect assets to portfolio
fix images for assets page. 
Ticket #
=> redirect assets to portfolio

CHANGELOG.md, Dockerfile.e2e, apps/mission/e2e/cleanupTabs.ts, apps/mission/e2e/copilot.nonetwork.spec.ts, apps/mission/e2e/copilot.spec.ts, apps/mission/e2e/dappstore.spec.ts, apps/mission/tsconfig.json, packages/copilot/package.json, packages/copilot/src/__tests__/TopUp.WithMixpanelToken.spec.tsx, packages/copilot/src/__tests__/TopUp.WithoutMixpanelToken.spec.tsx, packages/copilot/src/copilot/steps/topUp/TopUp.tsx, packages/copilot/src/copilot/steps/topUp/utils.tsx, packages/test-utils/playwright/fixtures/keplr.ts, packages/test-utils/playwright/fixtures/metamask-utils.ts, packages/test-utils/playwright/fixtures/metamask.ts, packages/test-utils/playwright/playwright.shared.config.ts, packages/test-utils/playwright/utils/keplr/download-release.ts, packages/test-utils/tsconfig.json, turbo.json
fix: change layerSwap to layerswap
Ticket #fse-801
=> fix: change layerSwap to layerswap

packages/constants-helper/src/constants.ts, packages/constants-helper/src/index.ts, pages/dappstore/src/dappStore/HeroSection.tsx
Add tally link to add your dapp button
Ticket #fse-848
=> add link to add your dapp button

packages/config/tailwind/base.js, packages/ui-helpers/src/badges/Badge.tsx, packages/ui-helpers/src/breadcrumbs/Breadcrumb.tsx, packages/ui-helpers/src/index.tsx, packages/ui-helpers/src/titles/Title.tsx, pages/dappstore/src/dappExplorer/ExplorerdApps.tsx, pages/dappstore/src/dappExplorer/data.ts, pages/dappstore/src/index.tsx
- Add component for breadcrumbs
- Add categories using the badge component. Create a new variant
- 
Ticket #fse-853
=> breadcrumbs and categories with dapps

packages/instant-dapps/src/dapps/Layerswap.tsx, packages/ui-helpers/src/container/FrameLine.tsx, pages/dappstore/src/pages/dapp-explorer/partials/description-section.tsx
Add styles for layerswap instant dapp
Update contact details for technical information
Ticket #fse-827
=> feat: add styles for layerswap instant dapp

packages/instant-dapps/src/dapps/Squid.tsx
Add styles for squid instant dapp
Ticket #fse-830
=> feat: add styles for squid instant dapp

packages/instant-dapps/src/dapps/C14.tsx, pages/dappstore/src/pages/dapp-explorer/partials/description-section.tsx, pnpm-lock.yaml
Update styles for c14 widget and add it on widgets list
Ticket #fse-828
=> update styles for c14 widget and add it on widgets list

packages/instant-dapps/src/dapps/C14.tsx, packages/instant-dapps/src/dapps/Layerswap.tsx, packages/instant-dapps/src/dapps/Squid.tsx, packages/instant-dapps/src/dapps/Transak.tsx, pages/dappstore/src/pages/dapp-explorer/partials/description-section.tsx
update styles for transak widget and add it on widgets list
Ticket #fse-829
=> update styles for transak widget and add it on widgets list

packages/i18n/locales/en/dappStore.json, pages/dappstore/src/pages/dapp-explorer/dapp-explorer-page.tsx, pages/dappstore/src/pages/dapp-explorer/partials/description-section.tsx, pages/dappstore/src/pages/dapp-explorer/partials/header-categories.tsx, pages/dappstore/src/pages/landing/landing-page.tsx, pages/dappstore/src/pages/landing/partials/ecosystem-section.tsx, pages/dappstore/src/pages/landing/partials/hero-section.tsx
add localization for dappstore
Ticket #fse-866
=> add localization for dappstore

apps/mission/src/components/header/Header.tsx, packages/icons/src/WebsiteIcon.tsx, packages/ui-helpers/src/badges/Badge.tsx, packages/ui-helpers/src/breadcrumbs/Breadcrumb.tsx, packages/ui-helpers/src/container/FrameLine.tsx, pages/dappstore/src/pages/dapp-explorer/partials/description-link.tsx, pages/dappstore/src/pages/dapp-explorer/partials/description-section.tsx, pages/dappstore/src/pages/dapp-explorer/partials/header-categories.tsx, pages/dappstore/src/pages/landing/landing-page.tsx, pages/dappstore/src/pages/landing/partials/account-balance.tsx, pages/dappstore/src/pages/landing/partials/ecosystem-card-grid.tsx, pages/dappstore/src/pages/landing/partials/ecosystem-card.tsx, pages/dappstore/src/pages/landing/partials/ecosystem-section.tsx, pages/dappstore/src/pages/landing/partials/hero-section.tsx, pnpm-lock.yaml
Update styles to match the figma file
Ticket #fse-876
=> feat: pixel perfection

CHANGELOG.md, package.json
- (chore fse-880) | packages/registry 1.0.5 | add KAVA token
- (chore) fse-867 | apps/vesting 1.1.5 | approve step for funding vesting account
=> Release v1.3.10

packages/helpers/src/parse/index.tsx, packages/helpers/src/parse/urls.ts, pages/dappstore/src/lib/schemas/entities/dappSchema.ts, pages/dappstore/src/pages/dapp-explorer/partials/description-section.tsx
Add parsing urls for telegram, discord, twitter, etc.
Ticket #fse-879
=> feat: parse urls

apps/mission/src/components/header/Branding.tsx, pages/dappstore/src/pages/dapp-explorer/partials/description-item.tsx, pages/dappstore/src/pages/dapp-explorer/partials/description-section.tsx, pages/dappstore/src/pages/dapp-explorer/partials/header-categories.tsx, pages/dappstore/src/pages/landing/partials/account-balance.tsx, pages/dappstore/src/pages/landing/partials/ecosystem-section.tsx, pages/dappstore/src/pages/landing/partials/hero-section.tsx, pages/portfolio/src/modals/transfer/TransferModalContent.tsx, pages/staking/src/components/staking/modals/Staking.tsx
Update mobile version
Ticket #fse-852
=> update mobile version

packages/instant-dapps/package.json, packages/instant-dapps/src/dapps/Forge.tsx, pages/dappstore/src/pages/dapp-explorer/partials/description-section.tsx, pnpm-lock.yaml
=> chore: Add forge widget

packages/config/tailwind/base.js, packages/evmos-wallet/src/hooks/rewards/fetch.ts, packages/ui-helpers/src/badges/Badge.tsx, packages/ui-helpers/src/modal/TokenCard.tsx, packages/ui-helpers/src/titles/Subtitle.tsx, pages/dappstore/src/pages/dapp-explorer/partials/description-section.tsx, pages/dappstore/src/pages/dapp-explorer/partials/header-categories.tsx, pages/dappstore/src/pages/landing/partials/ecosystem-card.tsx, pages/dappstore/src/pages/landing/partials/hero-section.tsx, pages/governance/src/utils/transactions/fetch.ts, pages/portfolio/src/asset/dropdown/DropdownTokens.tsx, pages/portfolio/src/asset/modals/transactions/Convert.tsx, pages/portfolio/src/asset/modals/transactions/hooks/useConvert.ts, pages/portfolio/src/utils/fetch.ts, pages/portfolio/src/utils/transactions/ibcTransfer.ts, pages/staking/src/utils/transactions/fetch.ts, pages/vesting/src/components/vesting/content/modal/AccountContent.tsx, pages/vesting/src/components/vesting/content/modal/AmountItem.tsx, pages/vesting/src/components/vesting/header/EnableVestingModal.tsx, pages/vesting/src/components/vesting/header/Header.tsx, pages/vesting/src/components/vesting/helpers.ts
remove some todos and add colors to tailwind
Ticket #fse-866
=> remove some todos and add colors to tailwind

CHANGELOG.md, apps/staking/package.json, apps/staking/src/components/staking/modals/hooks/useDelegation.tsx, apps/staking/src/internal/staking/functionality/hooks/useStakingPrecompile.ts
=> chore: add zero value to staking transactions

apps/mission/src/globals.css, pages/governance/src/components/governance/proposalPage/DescriptionItem.tsx, pages/governance/src/components/governance/proposalPage/ProposalDescription.tsx
Update governaace font size
Ticket #
=> fix: governance font size

CHANGELOG.md, package.json
- (chore) fse-896 | apps/staking 1.1.4 | add zero values to staking precompiles call
=> v1.3.12 release

pages/dappstore/src/pages/landing/partials/hero-section.tsx
Add dots in the corner for hero section
Ticket #fse-891
=> update for hero section

apps/mission/src/components/header/Branding.tsx, apps/mission/src/components/header/LaunchPad.tsx, packages/copilot/src/setup-account/steps/setup-success-step.tsx, pages/portfolio/src/asset/table/components/Description.tsx, pages/staking/src/components/staking/components/TopBarStaking.tsx, pages/staking/src/components/staking/components/stateful-countdown.tsx, pages/staking/src/utils/hooks/useEpochDay.tsx
Fix size warning for logo
Fix size warning for launchpad
Fix close icon position on modal
Fix size warning for assets table 
Fix hydration for countdown
Ticket #fse-902
=> fix: errors and warnings

packages/evmos-wallet/src/hooks/rewards/useRewards.tsx, pages/dappstore/src/pages/landing/partials/staking-card/index.tsx, pages/staking/src/components/staking/components/TopBarStaking.tsx, pnpm-lock.yaml
Disable claim rewards button if the user already click on it to get the rewards. 
Ticket #fse-871
=> fix: disable claim rewards

apps/mission/src/components/footer/Footer.tsx, packages/ui-helpers/src/Footer.tsx
Update build with us footer link
Ticket #fse-929
=> chore: update build with us footer link

apps/mission/src/components/footer/Footer.tsx
Fix: hover on footer
Ticket #fse-914
=> fix: hover on footer

packages/i18n/locales/en/dappStore.json
Update text for hero section button
Ticket #fse-918
=> chore: update text for hero section button

apps/mission/src/components/footer/Footer.tsx, apps/mission/src/components/footer/cookies-settings.tsx, pages/dappstore/src/pages/landing/partials/account-balance.tsx
- change topup color
- fix event for cookies settings
Ticket #fse-920
=> chore: change topup color and fix event for cookies settings

pages/dappstore/src/pages/dapp-explorer/partials/description-section.tsx, pages/dappstore/src/pages/landing/partials/ecosystem-section.tsx
Center text on mobile so it's align with button text
Ticket #fse-917
=> fix: align text with button on mobile

apps/mission/src/components/header/LaunchPad.tsx
Close launchpad after click
Ticket #
=> fix: close launchpad after click

apps/assets/src/components/asset/table/AssetsTable.tsx
=> fix: remove text

packages/copilot/src/topup/steps/topup-entry-step.tsx
Reduce spacing in copilot topup to half
Ticket #fse-934
=> fix: reduce spacing in copilot topup

pages/dappstore/src/pages/landing/partials/hero-section.tsx
Switch hero section components
Ticket #fse-930
=> chore: switch hero section components

packages/widgets/src/Stride/Stride.tsx, packages/widgets/src/Stride/query-evmos-values.tsx
fix: available balance stride. Update evmos price getter
Ticket #
=> fix: available balance stride. Update evmos price getter

apps/assets/src/components/asset/modals/transactions/Convert.tsx, apps/assets/src/components/asset/modals/transactions/hooks/useConvert.ts, apps/vesting/src/components/vesting/content/modal/ClawbackModal.tsx, apps/vesting/src/components/vesting/header/ApproveFunding.tsx, apps/vesting/src/components/vesting/header/EnableVestingModal.tsx, apps/vesting/src/components/vesting/header/ExecuteFund.tsx, apps/vesting/src/components/vesting/header/FundVestingAccount.tsx
Fix: remove extra slash on tx link for
- convert tnxs
- vesting txns
Ticket #fse-865
=> fix: remove extra slash on tx link

apps/mission/next.config.mjs, pnpm-lock.yaml, turbo.json
=> Sets vercel redirects

packages/stateful-components/src/modals/ConnectModal/ConnectModalContent.tsx
Add icon on evmos copilot text so every box has an icon.
Ticket #fse-939
=> chore: add icon on evmos copilot

apps/mission/src/app/[locale]/layout.tsx, packages/ui-helpers/src/banners/Banner.tsx
Change disruption banner position
Ticket #fse-931
=> chore: change disruption banner position

pages/portfolio/src/modals/request/ReceiveContent.tsx
Fix toggle address format for receive modal. 
On the refactor some logic was removed. Added back
Ticket #fse-948
=> fix: toggle address format for receive modal

packages/stateful-components/src/modals/ConnectModal/coming-soon-wallets.tsx
Change badge color for coming soon wallets. Replace danger for success
Ticket #fse-945
=> fix: change badge color for coming soon wallets

packages/widgets/src/Stride/Stride.tsx
Change url for learn more on stride widget
Ticket #
=> fix: change url for learn more on stride widget

apps/mission/next.config.mjs
=> fix wrong redirect destination

apps/mission/next.config.mjs
=> adds redirect from assets to portfolio

CHANGELOG.md, apps/mission/next.config.mjs, package.json
- (chore) add redirect from /assets to /portfolio
=> Release v1.3.14

CHANGELOG.md, apps/mission/next.config.mjs, package.json
=> Merge main

CHANGELOG.md, packages/evmos-wallet/package.json, packages/evmos-wallet/src/registry-actions/index.ts, packages/evmos-wallet/src/registry-actions/transfers/prepare-contract-ibc-transfer.ts, packages/widgets/package.json, packages/widgets/src/Osmosis/memoGenerator.test.ts, packages/widgets/src/Osmosis/memoGenerator.tsx, packages/widgets/src/Osmosis/useOsmosisPrecompile.tsx, packages/widgets/src/Stride/Stride.tsx, packages/widgets/src/Stride/memoGenerator.test.ts, packages/widgets/src/Stride/memoGenerator.ts, packages/widgets/src/Stride/useStridePrecompile.tsx
=> feat: move memoGenerator to apps repo

.husky/pre-commit
=> fix: remove set upstream from pre-commit

CHANGELOG.md, packages/i18n/locales/en/dappStore.json, packages/i18n/package.json, pages/dappstore/package.json, pages/dappstore/src/pages/landing/partials/copilot-card/copilot-card.tsx
Fix: copilot card colors and text
Remove `Stake` button
Ticket #fse-950
=> fix: copilot card colors and text

CHANGELOG.md, packages/helpers/package.json, packages/helpers/src/clients/cosmos.ts, packages/helpers/src/clients/get-pub-url.ts, packages/helpers/src/evmos-info.ts, turbo.json
=> Add vercel url to turbo config

packages/trpc/src/procedures/account/fetch-account-balance-by-denom.ts
=> Fix account balance fetching  error

CHANGELOG.md, packages/constants-helper/package.json, packages/constants-helper/src/index.ts
Update link for give us feedback: use tally instead of canny
Ticket #
=> chore: change link for give us feedback

packages/widgets/package.json, pnpm-lock.yaml
=> update stride widget dependency

apps/mission/package.json, packages/copilot/package.json, packages/i18n/package.json, packages/stateful-components/package.json, pages/portfolio/src/modals/request/ReceiveContent.tsx, pnpm-lock.yaml
=> Fix typescript error

packages/helpers/src/clients/get-pub-url.ts
=> adds absolute url to rpcs on wagmi config

CHANGELOG.md, packages/widgets/package.json, pnpm-lock.yaml
Upgrades Forge widget to version `1.2.8`
=> Forge widget upgrade

CHANGELOG.md, pages/portfolio/package.json, pages/portfolio/src/modals/shared/AccountSelector.tsx, pages/portfolio/src/modals/transfer/TransferModalContent.tsx
Allow sending axl based assets between evmos accounts
Ticket #fse-892
=> feat: allow sending axl based assets between evmos accounts

CHANGELOG.md, apps/mission/package.json, apps/mission/src/components/footer/Footer.tsx
update main version for dappstore. It was using the one related to mission
Ticket #fse-967
=> fix: update main version (footer)

CHANGELOG.md, packages/ui-helpers/package.json, packages/ui-helpers/src/widgets/Mava.tsx
Update mava script
Ticket #fse-971
=> update mava script

CHANGELOG.md, packages/tracker/package.json, packages/tracker/src/events.ts, packages/widgets/package.json, packages/widgets/src/Osmosis/useOsmosisPrecompile.tsx, packages/widgets/src/Stride/useStridePrecompile.tsx
Set up tracking whether txns are successful or not for Stride & Osmosis Instant dApps
Ticket #onb-6
=> feat: track widget transactions

CHANGELOG.md, package.json
- (fix) xap-125 | apps 1.0.30 packages/copilot 1.0.13 packages/icons 1.0.12 packages/instantdapps 1.0.1 packages/widgets 1.0.3 pages/dappsstore 1.1.5 | Remove Cypher from instant dapps
- (chore) | packages/widgets 1.0.3 packages/tracker 1.0.10 | Track widget transactions
=> Release version 2.0.4

CHANGELOG.md, package.json
=> release v2.0.5

CHANGELOG.md, apps/mission/package.json, apps/mission/src/components/header/evmos-price/EvmosPrice.tsx, apps/mission/src/components/header/evmos-price/PriceDisplay.tsx
Adds error boundary around evmos price
Ticket #
=> adds error boundary around evmos price

CHANGELOG.md, package.json
=> release v.2.0.6

CHANGELOG.md, apps/mission/package.json, packages/config/package.json, packages/constants-helper/package.json, packages/evmos-wallet/package.json, packages/evmos-wallet/src/wallet/wagmi/cosmos-providers/cosmos-eip1193-provider.ts, packages/helpers/package.json, packages/stateful-components/package.json, packages/trpc/package.json, packages/ui-helpers/package.json, pages/dappstore/package.json, pages/portfolio/package.json
sendTransaction was failing while trying to send EVMOS from Evmos to Evmos. Update request call to use public provider for methods that are not defined. 
Ticket #
=> fix: update request provider

packages/evmos-wallet/src/api/utils/sign-api-presign-tx.ts
Add check for cosmos based wallets
Ticket #
=> fix: add check for cosmos based wallets

packages/trpc/src/procedures/tokens/queries/fetch-tokens.ts, packages/trpc/src/procedures/utils/fetch-chain-registry-dir.ts
=> feat: using proxy.evmos.org to get github data

packages/trpc/src/procedures/utils/fetch-chain-registry-dir.ts
=> fix: use proxy for everything related to github

CHANGELOG.md, packages/i18n/locales/en/portfolio.json, packages/i18n/package.json, packages/ui-helpers/package.json, packages/ui-helpers/src/PrimaryButton.tsx, pages/portfolio/package.json, pages/portfolio/src/asset/table/AssetsTable.tsx, pages/portfolio/src/asset/table/ContentTable.tsx, pages/portfolio/src/asset/table/topBar/TopBar.tsx, pages/portfolio/src/utils/hooks/useDataTokens.tsx, pages/portfolio/src/utils/tokens/tokenUtils.tsx
Add a button to add tokens to MetaMask in portfolio page
Ticket #
=> add metamask btn

CHANGELOG.md, packages/ui/package.json, packages/ui/src/chips/Chip.stories.tsx, packages/ui/src/chips/Chip.tsx
Basic chip configuration using storybooks.
Ticket #
=> Storybooks Chips

CHANGELOG.md, package.json
- (feat) pages/governance 1.1.4 | Read blocked proposals from notion
- (fix) dapp-58 | pages/dappstore | Update ecosystem section - show 8 dapps
=> Release 2.0.13

apps/mission/src/components/footer/Footer.tsx, packages/i18n/locales/en/common.json, packages/stateful-components/src/modals/ConsentModal/ConsentModal.tsx, packages/stateful-components/src/modals/TermsOfServices/TermsOfServiceController.tsx, packages/stateful-components/src/modals/TermsOfServices/TermsOfServiceModal.tsx, packages/ui/src/components/dialog/Dialog.tsx
Update ToS modal
Ticket #dapp-34
=> update modal for terms of service

packages/ui/src/components/listboxs/listbox.tsx, pages/dappstore/src/lib/sort/sort-dapps.ts, pages/dappstore/src/pages/dapp-explorer/dapp-explorer-page.tsx, pages/dappstore/src/pages/dapp-explorer/partials/filter-apps.tsx
Add desc sorting for categories
Ticket #dapp-81
=> add desc sorting for categories

packages/ui-helpers/src/breadcrumbs/Breadcrumb.tsx
fix: remove breadcrumbs from categories page on mobile
Ticket #dapp-83
=> fix: remove breadcrumbs from categories page on mobile

apps/mission/src/components/header/signin/useSignIn.tsx, packages/i18n/locales/en/dappStore.json
fix: show all wallets on modal
Ticket #dapp-88
=> fix: show all wallets on modal

apps/mission/src/components/header/edit/ModalEdit.tsx, apps/mission/src/components/header/signin/useSignIn.tsx, packages/ui/src/components/alert/Alert.stories.tsx, packages/ui/src/components/alert/index.tsx
Add alerts for sign in flow
Ticket #dapp-62
=> add alerts for sign in flow

apps/mission/src/components/header/signin/Profile.tsx, packages/tracker/src/events.ts, pages/dappstore/src/lib/sort/sort-dapps.ts, pages/dappstore/src/pages/dapp-explorer/partials/description-section.tsx, pages/dappstore/src/pages/dapp-explorer/partials/filter-apps.tsx, pages/dappstore/src/pages/landing/partials/ecosystem-card.tsx, pages/dappstore/src/pages/landing/partials/fetchPageDynamicSections.tsx
feat: newly added into sorting logic
Ticket #dapp-80
=> feat: show newly added into sorting logic

apps/mission/src/app/[locale]/layout.tsx, apps/mission/src/components/footer/Footer.tsx, pages/dappstore/src/pages/dapp-explorer/partials/filter-apps.tsx
fix: padding layout for mobile
Ticket #dapp-81
=> fix: padding layout for mobile

pages/dappstore/src/pages/dapp-explorer/partials/filter-apps.tsx
fix: reduce padding on filter apps
Ticket #dapp-78
=> fix: reduce padding on filter apps

pages/dappstore/src/pages/dapp-explorer/dapp-explorer-page.tsx
fix padding breadcrumb explorer page
Ticket #dapp-86
=> fix padding breadcrumb explorer page

packages/ui/src/components/dropdown/Dropdown.tsx, pages/dappstore/src/pages/dapp-explorer/dapp-explorer-page.tsx, pages/dappstore/src/pages/dapp-explorer/partials/filter-apps.tsx, pages/dappstore/src/pages/dapp-explorer/partials/header-categories.tsx
fix: reduce width in the wallet modal
Ticket #dapp-89
=> fix: reduce width in the wallet modal

apps/mission/src/components/header/signin/WalletsModal.tsx, packages/ui/src/global.css
Hide scrollbar on wallets modal
Ticket #dapp-93
=> chore: hide scrollbar on wallets modal

apps/mission/src/components/footer/Footer.tsx
Add GitHub on footer mobile version
Ticket #dapp-92
=> chore: add GitHub on footer mobile version

apps/mission/src/components/ContainerLogo.tsx, apps/mission/src/components/header/Header.tsx, apps/mission/src/components/useResize.tsx
fix: skeleton for sign in. 
Ticket #dapp-94
=> fix: skeleton for sign in

apps/mission/src/components/FavoriteSection.tsx, apps/mission/src/components/Sidebar.tsx, apps/mission/src/components/header/signin/Settings.tsx, apps/mission/src/components/header/signin/StepsSignIn.tsx, packages/ui/src/components/dropdown/Dropdown.tsx, pages/dappstore/src/pages/landing/ScrollableSection.tsx, pages/dappstore/src/pages/landing/partials/DynamicSections.tsx
- Add empty state for favorites
- Change layout for landing page on categories section
- Update sidebar names and remove develop
- update width for dropdown sign in
- change link for cards and update instant dapp that was not showing
Ticket #
=> fixes v2 dappstore

apps/mission/src/components/FavoriteSection.tsx, packages/i18n/locales/en/dappStore.json
fix: typo on favorite section
Ticket #dapp-96
=> fix: typo and add i18n for favorite section

apps/mission/src/components/Sidebar.tsx, packages/i18n/locales/en/dappStore.json
fix: space and add i18n to sidebar
Ticket #dapp-99
=> fix: space and add i18n to sidebar

pages/dappstore/src/pages/dapp-explorer/partials/header-categories.tsx
fix: show correct amounts of dapps filtered by instant dapps
Ticket #dapp-107
=> fix: show correct amounts of dapps filtered by instant dapps

pages/dappstore/src/pages/dapp-explorer/dapp-explorer-page.tsx, pages/dappstore/src/pages/dapp-explorer/partials/header-categories.tsx
fix: add instant dapp text when filtering
Ticket #dapp-108
=> fix: add instant dapp text when filtering

pages/dappstore/src/pages/landing/landing-page.tsx
fix: remove container classname from landingpage
Ticket #dapp-106
=> remove container classname from landingpage

packages/i18n/locales/en/dappStore.json, pages/dappstore/src/pages/dapp-explorer/share-dropdown.tsx
chore: add default text when sharing
Ticket #dapp-103
=> add default text when sharing

pages/dappstore/src/pages/dapp-explorer/partials/carousel.tsx
fix: pixelated images on gallery
Ticket #dapp-114
=> fix: pixelated images on gallery

pages/dappstore/src/pages/landing/partials/DynamicSections.tsx
fix: add tags and instant dapps on trending
Ticket #dapp-116
=> add tags and instant dapps on trending

apps/mission/src/components/header/signin/Profile.tsx, packages/ui-helpers/src/CopyButton.tsx, packages/ui-helpers/src/Tooltip.tsx, packages/ui-helpers/src/index.tsx, pages/dappstore/src/pages/dapp-explorer/share-dropdown.tsx
=> reuse copy button

pages/dappstore/src/pages/dapp-explorer/share-dropdown.tsx
use the component Dropdown for share button
Ticket #dapp-120
=> chore: use dropdown on share-dropdown

pages/dappstore/src/pages/dapp-explorer/partials/description-section.tsx
add one liner on details page
Ticket #dapp-123
=> chore: add one liner on details page

pages/dappstore/src/pages/dapp-explorer/partials/description-section.tsx, pages/dappstore/src/pages/dapp-explorer/partials/favorite-button.tsx
- disable favorite is user is not connected
- fix instant dapp layout on details page
Ticket #
=> disable favorite is user is not connected

packages/stateful-components/src/modals/TermsOfServices/TermsOfServiceController.tsx
update styles tos modal
Ticket #dapp-126
=> update styles for tos modal

pages/dappstore/src/pages/dapp-explorer/partials/no-page-found.tsx
fix: center text on mobile
Ticket #dapp-132
=> fix: center text on mobile

apps/mission/vitest.setup.ts
This PR enables mixpanel  pageview events
=> Enable mixpanel pageviews

pages/dappstore/src/pages/dapp-explorer/share-dropdown.tsx
Adds UTM params on share links to be tracked by mix panel
=> chore: Add UTM parans to share links

apps/mission/src/components/ContainerLogo.tsx, apps/mission/src/components/Sidebar.tsx
issues: 
- Nav Bar with Evmos logo isn't aligned correctly
- Increase spacing between icon and text
- Font color is incorrect in hover state
Ticket #
=> Sidebar fix

packages/stateful-components/src/modals/ConsentModal/ConsentModal.tsx, pages/dappstore/src/pages/landing/partials/banner-card.tsx
update gradient on banner card
Ticket #dapp-119
=> update gradient on banner card

apps/mission/src/components/FavoriteSection.tsx, apps/mission/src/components/header/Header.tsx, apps/mission/src/components/header/signin/useSignIn.tsx, apps/mission/src/components/search/Search.tsx, apps/mission/src/components/search/SearchResults.tsx, packages/stateful-components/src/connect-button.tsx, packages/tracker/src/events.ts, packages/ui-helpers/src/CopyButton.tsx, pages/dappstore/src/pages/dapp-explorer/partials/description-section.tsx, pages/dappstore/src/pages/dapp-explorer/partials/favorite-button.tsx, pages/dappstore/src/pages/dapp-explorer/share-dropdown.tsx, pages/dappstore/src/pages/landing/partials/DynamicSections.tsx
- add alert when user clicks on copy to clipboard
- add mixpanel events
Ticket #dapp-90 #dapp-127
=> mixpanel events and alert for copy to clipboard

pages/dappstore/src/pages/landing/partials/ecosystem-card.tsx
=> Fix: card shadow effect

apps/mission/src/components/Sidebar.tsx
update sidebar selected status
Ticket #dapp-95
=> update sidebar selected status

apps/mission/src/components/Sidebar.tsx
add bg to selected status on sidebar
Ticket #dapp-136
=> add bg to selected status on sidebar

apps/mission/src/components/Sidebar.tsx
=> update sidebar bg

apps/mission/src/components/FavoriteSection.tsx, packages/stateful-components/src/connect-button.tsx, packages/tracker/src/events.ts, packages/ui/src/components/listboxs/listbox.tsx, pages/dappstore/src/pages/dapp-explorer/dapp-explorer-page.tsx, pages/dappstore/src/pages/dapp-explorer/partials/dapps-results.tsx, pages/dappstore/src/pages/dapp-explorer/partials/filter-apps.tsx, pages/dappstore/src/pages/dapp-explorer/partials/use-filtered-dapps.tsx
- add event for removing favorite (sidebar)
- add and change dynamic section for categories and details page
Ticket #
=> fixes for dappstore v2

packages/ui/src/global.css
=> fix: add disabled state to globals.css

apps/mission/src/components/FavoriteSection.tsx, pages/dappstore/src/pages/landing/partials/banner-card.tsx
=> fix banner

packages/helpers/src/evmos-info.ts, pages/dappstore/src/pages/dapp-explorer/partials/description-section.tsx
=> reuse evmos-eth-json-rpc

packages/i18n/locales/en/common.json
=> update tos text for cta button

apps/mission/src/app/[locale]/layout.tsx, apps/mission/vitest.setup.ts, packages/instant-dapps/src/dapps/LeapElements.tsx, packages/tracker/src/useTracker.tsx, packages/ui/src/components/inputs/Input.tsx, packages/ui/src/global.css, pages/dappstore/src/pages/dapp-explorer/share-dropdown.tsx
- tracking updates
- removing code that was not used
- fix styles
Ticket #dapp-140
=> fixes dappstore v2 part ii

pages/dappstore/src/pages/landing/partials/DynamicSections.tsx
=> fix shadow

apps/mission/src/components/Sidebar.tsx, apps/mission/src/components/header/edit/ModalEdit.tsx, apps/mission/src/components/header/signin/ProfileButton.tsx, packages/ui/src/components/dialog/Dialog.stories.tsx, packages/ui/src/components/dialog/Dialog.tsx, packages/ui/src/components/dropdown/Dropdown.stories.tsx, packages/ui/src/components/listboxs/Listbox.stories.tsx, packages/ui/src/components/listboxs/listbox.tsx, packages/ui/src/global.css, pages/dappstore/src/pages/dapp-explorer/partials/filter-apps.tsx
=> fix: sidebar active

apps/mission/src/components/Sidebar.tsx
fix space for socials on sidebar
Ticket #
=> fix: space socials sidebar

apps/mission/src/app/[locale]/layout.tsx
=> fix: change siteName on openGraph

packages/ui-helpers/src/CopyButton.tsx
=> chore: remove alert for copy

CHANGELOG.md, apps/mission/src/app/[locale]/layout.tsx, apps/mission/src/components/Sidebar.tsx, pages/dappstore/package.json, pages/dappstore/src/pages/dapp-explorer/dapp-explorer-page.tsx, pages/dappstore/src/pages/dapp-explorer/partials/CategoryHeader.tsx, pages/dappstore/src/pages/dapp-explorer/partials/filter-apps.tsx, pages/dappstore/src/pages/dapp-explorer/partials/header-categories.tsx, pages/dappstore/src/pages/landing/ScrollableSection.tsx, pages/dappstore/src/pages/landing/partials/DynamicSections.tsx
=> Styling adjustments to landing and category page

apps/mission/src/components/FavoriteSection.tsx
=> fix: avoid redirecting after removing dapp from favorites

CHANGELOG.md, apps/mission/package.json, apps/mission/src/components/Sidebar.tsx
=> fix Highlight

CHANGELOG.md, apps/mission/package.json, apps/mission/src/components/header/edit/ModalEdit.tsx
The image displayed on the profile could not be changed correctly.
Ticket #
=> fix profile picture

CHANGELOG.md, packages/evmos-wallet/src/api/cosmos-rest/api-cosmos-account-by-address.ts, packages/evmos-wallet/src/registry-actions/transfers/prepare-cosmos-ibc-transfer.ts, packages/evmos-wallet/src/registry-actions/utils/create-protobuf-transaction.ts, packages/evmos-wallet/src/registry-actions/utils/get-chain-account-info.ts, pages/portfolio/package.json
=> Fix account info request

.changeset/cold-wombats-compare.md, .changeset/nasty-ties-give.md, .changeset/neat-sloths-burn.md, .changeset/thirty-ladybugs-travel.md, apps/mission/CHANGELOG.md, apps/mission/package.json, packages/scripts/CHANGELOG.md, packages/scripts/package.json, pages/portfolio/CHANGELOG.md, pages/portfolio/package.json, pages/staking/CHANGELOG.md, pages/staking/package.json
PATCH @evmosapps/portfolio-page@1.1.13
- Fix account info request
PATCH dappstore@2.0.18
- Fix profile picture
MINOR @evmosapps/scripts@1.1.0
- Implements release script
PATCH @evmosapps/staking-page@1.1.6
- Refactor and fix claim rewards, fix testnet setup
=> Release dappstore: 2.0.18

packages/scripts/release/release.ts
I forgot to disable draft mode on the release script, and apparently my ide forgot to autoformat the file
Ticket #
=> Remove draft mode from release PR script

apps/mission/src/app/[locale]/layout.tsx, apps/mission/src/components/warning/reconnect-wallet.tsx, packages/i18n/locales/en/dappStore.json, packages/ui/src/components/alert/index.tsx
=> Re connect alert

apps/mission/src/components/header/signin/ModalDeleteProfile.tsx, apps/mission/src/components/header/signin/Settings.tsx, apps/mission/src/components/modals.tsx, packages/i18n/locales/en/dappStore.json, packages/ui/src/components/checkboxs/checkbox.tsx, packages/ui/src/components/dialog/Dialog.tsx, packages/ui/src/components/dropdown/Dropdown.tsx
Add modal for deleting profile
Ticket #dapp-174
=> feat: create modal for delete profile

apps/mission/src/app/[locale]/layout.tsx, apps/mission/src/components/header/signin/ManageProfileModal.tsx, apps/mission/src/components/header/signin/Signin/CancelModalBody.tsx, apps/mission/src/components/header/signin/Signin/Modal.tsx, apps/mission/src/components/header/signin/Signin/SigninModalBody.tsx, apps/mission/src/components/modals.tsx, apps/mission/src/components/warning/mismatch-address.tsx, packages/i18n/locales/en/dappStore.json
alert & modal for managing profiles
Ticket #dapp-177
=> feat: alert & modal for managing profiles

apps/mission/src/components/header/signin/ModalReConnect.tsx, apps/mission/src/components/modals.tsx, apps/mission/src/components/warning/reconnect-wallet.tsx, packages/i18n/locales/en/dappStore.json, packages/ui/src/components/alert/index.tsx
=> reconnect modal

apps/mission/src/components/header/signin/ManageProfileModal.tsx, packages/ui/src/components/spinners/Spinner.tsx, packages/user/src/auth/next-auth.d.ts
add spinner when clicking on sign in
Ticket #dapp-178
=> add spinner when clicking on sign in

apps/mission/src/components/header/signin/ManageProfileModal.tsx, apps/mission/src/components/modals.tsx, apps/mission/src/components/warning/mismatch-address.tsx, packages/i18n/locales/en/dappStore.json, packages/stateful-components/package.json, packages/stateful-components/src/modals/ConfirmEVMTxModal.tsx, packages/user/src/auth/next-auth.d.ts, pnpm-lock.yaml
create modal for submitting evm txns
Ticket #dapp-179
=> feat: create modal for submitting evm txns

apps/mission/src/components/modals.tsx, packages/i18n/locales/en/dappStore.json, packages/stateful-components/src/modals/ConfirmCosmosTxModal.tsx
create modal for cosmos tx
Ticket #dapp-180
=> feat: create modal for cosmos tx

apps/mission/src/components/header/edit/useEdit.tsx, apps/mission/src/components/header/signin/ProfileButton.tsx, apps/mission/src/components/header/signin/Settings.tsx, apps/mission/src/components/header/signin/useSignIn.tsx
update: welcoming alert
Ticket #dapp-181
=> update: welcoming alert

apps/mission/src/components/warning/mismatch-address.tsx, apps/mission/src/components/warning/reconnect-wallet.tsx
=> Fix reconnect warning

apps/mission/src/components/header/Header.tsx, apps/mission/src/components/header/SearchButton.tsx, apps/mission/src/components/header/SiweExample.tsx, apps/mission/src/components/header/signin/Profile.tsx, apps/mission/src/components/header/signin/ProfileButton.tsx, apps/mission/src/components/header/signin/Settings.tsx, apps/mission/src/components/header/signin/StepsSignIn.tsx, apps/mission/src/components/header/signin/SuspenseBoundary.tsx, apps/mission/src/components/header/signin/Wallets.tsx, apps/mission/src/components/header/signin/signInParts.tsx, apps/mission/src/components/header/signin/useEvmosBalance.tsx, packages/evmos-wallet/src/wallet/components/WalletProvider.tsx, packages/stateful-components/package.json, packages/stateful-components/src/newFile.tsx, packages/stateful-components/src/root-providers.tsx, packages/testnet/src/cli/index.ts, packages/trpc/src/procedures/tokens/queries/price/fetch-token-prices.ts, packages/user/package.json, packages/user/src/api.test.ts, packages/user/src/api.ts, packages/user/src/auth/auth-options.ts, packages/user/src/auth/get-user-session.ts, packages/user/src/auth/next-auth.d.ts, packages/user/src/auth/sign-with-ethereum-provider.ts, packages/user/src/auth/use-user-session.ts, packages/user/src/client.ts, pnpm-lock.yaml
=> Handling user session and adapt connection modal
